@Kurs.Cache_HostAddress = http://localhost:5299

###
GET {{Kurs.Cache_HostAddress}}/message/
Accept: application/json

###

POST {{Kurs.Cache_HostAddress}}/post_msg/kkk
Content-Type: application/json
{"Message": "hjdgsf444444hjdsg"}
 
###
